import jsPDF from 'jspdf';

export const generateYieldReport = async (result) => {
  return new Promise((resolve, reject) => {
    try {
      // Create new PDF document
      const doc = new jsPDF();
      
      // Add logo or header
      doc.setFontSize(20);
      doc.setTextColor(40, 100, 40);
      doc.text('Yield Prediction Report', 105, 20, { align: 'center' });
      
      // Add date and time
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${result.predictionDate} at ${result.predictionTime}`, 105, 30, { align: 'center' });
      
      // Add separator line
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 35, 190, 35);
      
      // Farm Information Section
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text('Farm Information', 20, 50);
      
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      doc.text(`Crop: ${result.crop}`, 20, 60);
      doc.text(`State/Region: ${result.state}`, 20, 67);
      doc.text(`Area: ${result.area} hectares`, 20, 74);
      doc.text(`Fertilizer: ${result.fertilizer} kg`, 20, 81);
      doc.text(`Pesticide: ${result.pesticide} litres`, 20, 88);
      
      // Prediction Results Section
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text('Prediction Results', 20, 110);
      
      doc.setFontSize(12);
      doc.setTextColor(0, 100, 0);
      doc.text(`Yield per Hectare: ${result.predictedYield} ${result.units}`, 20, 120);
      doc.setTextColor(0, 0, 100);
      doc.text(`Total Production: ${result.production} ${result.units}`, 20, 130);
      
      // Recommendations Section
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text('Recommendations', 20, 150);
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      
      let yPosition = 160;
      result.recommendations.forEach((rec, index) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(`${index + 1}. ${rec}`, 25, yPosition);
        yPosition += 7;
      });
      
      // Add footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Farmer Assistance System - AI-Powered Yield Prediction', 105, 285, { align: 'center' });
      
      // Save the PDF
      const fileName = `Yield_Prediction_${result.crop}_${result.predictionDate.replace(/\//g, '-')}.pdf`;
      doc.save(fileName);
      
      resolve();
    } catch (error) {
      reject(error);
    }
  });
};